addr: "0.0.0.0:8080"

dvr:
  recordingsDir: "recordings"
  segmentDuration: 600
  snapshotInterval: 5
  ffmpegLog: false
  cameras: []

appUrl: "http://localhost:8081/panel/"
i2cDevice: "/dev/i2c-1"
pingInterval: "1s"

airSensor:
  address: 0x77
  interval: "1s"

expander:
  address: 0x20
  interval: "2ms"
  bits:
    joyCenter: 8
    joyDown: 9
    joyKnob: 13
    joyLeft: 12
    joyRight: 11
    joyUp: 10
    knobCenter: 0
    knobInner: 1
    knobOuter: 3
    led: 6

lightSensor:
  address: 0x48
  interval: "1s"

oled:
  dcPin: 5
  flip: true
  gpioChip: "gpiochip0"
  resetPin: 6
  spiPort: "/dev/spidev0.0"
  spiSpeed: "2.40MHz"

screen:
  fps: 30
  splashDuration: "2s"
  splashImage: "ui/public/img/logo.png"

tires:
  nose:
    - "4a:a0:00:00:eb:02"
    - "ae3806cb-ea50-2187-4d1d-10010147721a"
  left:
    - "4a:88:00:00:72:70"
    - "24237bb2-4496-36b6-a755-64e9de75ac6c"
  right:
    - "4a:85:00:00:d7:38"
    - "99633f0c-d627-5f15-7d5d-f171b5a745e7"

ui:
  tail: "N711ME"
  headerColor: "#3b82f6"
  panel:
    width: 256
    height: 64
  navMenu:
    hideDelay: 2000
    cellWidth: 64
  keyMap:
    up: ArrowUp
    down: ArrowDown
    left: ArrowLeft
    right: ArrowRight
    enter: Enter
    joyLeft: ","
    joyRight: .
    innerLeft: ;
    innerRight: "'"
    outerLeft: "["
    outerRight: "]"
